djangosite/mysite_first/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	#url(r'^auth/', admin.site.urls),
	url(r'^pools/', include('pools.urls')),
]

djangosite/mysite_first/pools/urls.py
from django.conf.urls import url
from . import views


app_name='pools'
urlpatterns = [
    # url(r'^hello$', views.index, name='index'),
	# url(r'^goods$', views.sogood, name='sogood'),
	# url(r'^getid_(?P<id>[\w]+)$', views.getid, name='getid'),
    # # ex: /pools/5/
    # url(r'^(?P<question_id>[0-9]+)/detail$', views.detail, name='detail'),
    # # ex: /pools/5/results/
    # url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # # ex: /pools/5/vote/
    # url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

djangosite/mysite_first/pools/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
import datetime
from django.utils import timezone

# Create your models here.
@python_2_unicode_compatible  # only if you need to support Python 2
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text
	
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
        #return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

@python_2_unicode_compatible  # only if you need to support Python 2
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
	
    def __str__(self):
        return self.choice_text
	
####################################################################	

djangosite/mysite_first/pools/views.py
from django.shortcuts import render,get_object_or_404
from django.template import loader
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import Question, Choice
from django.urls import reverse
from django.views import generic

# def index(request):
    # latest_question_list = Question.objects.order_by('pub_date')[:5:]
    # #222 template = loader.get_template('pools/index.html') # 获取HTML 的jinjia2页面
    # #111  output = ','.join([str(q.question_text)+'|||'  for q in latest_question_list])
    # context={
	    # 'latest_question_list':latest_question_list
		# }
    # #222  return HttpResponse(template.render(context, request))  # render 渲染整合模板和数据
    # #111  return HttpResponse(output)
    # return render(request, 'pools/index.html', context)


###########  MY VIEW #################################################
def myhtml5():
    return r"""
<html>
<body>
<h1>This is heading 1 </h1>
</body>
</html>
"""

def sogood(request):
    return HttpResponse(myhtml5())
	
def getid(request, id):
    return HttpResponse("get id:%s" %id)

##############################################################################
# def detail(request, question_id):
    # #try:
	# #    print(help(Question.objects.get))
	# #    question = Question.objects.get(pk=question_id)
    # #except Question.DoesNotExist:
    # #    raise Http404("Question dose not exist !")
    # #return render(request, 'pools/detail.html', {'question':question})
    # #return HttpResponse("You're looking at question %s." % question_id)
	
	# question = get_object_or_404(Question, pk=question_id)
	# return render(request, 'pools/detail.html', {'question':question})

	
# def results(request, question_id):
    # question = get_object_or_404(Question, pk=question_id)
    # return render(request, 'pools/results.html', {'question': question})
	
	
# def results(request, question_id):
    # question = get_object_or_404(Question, pk=question_id)
    # print(question.question_text)
    # #response = "You're looking at the results of question %s."
    # #return HttpResponse(response % question_id)
    # return render(request, 'pools/results.html', {'question':question})

def vote(request, question_id):
    #return HttpResponse("You're voting on question %s." % question_id)
	#def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'pools/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('pools:results', args=(question.id,)))
	
class IndexView(generic.ListView):
    template_name = 'pools/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'pools/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'pools/results.html'
	
	
	

djangosite/mysite_first/pools/templates/pools/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }} </strong></p>{% endif %}

<form action="{% url 'pools:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}

    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br/>
	
{% endfor %}
<input type="submit" value="Vote" />
</form>

djangosite/mysite_first/pools/templates/pools/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'pools/style.css' %}" />

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="/pools/{{ question.id }}">{{ question.question_text }}</a></li>
        <li><a href={% url 'pools:detail' question.id %}>{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No pools are available.</p>
{% endif %}

djangosite/mysite_first/pools/templates/pools/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all  %}
    <li>	{{ choice.choice_text}} -- {{ choice.votes}} vote {{ choice.votes|pluralize}}	</li>
{% endfor %}
</ul>
<a href="{% url 'pools:vote' question.id %}"> vote again ?</a>

<!-- <h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'pools:detail' question.id %}">Vote again?</a> -->